/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import javax.swing.JFrame;

/**
 *
 * @author Damian
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Access
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dispose();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        JpanelLogin = new javax.swing.JPanel();
        btnAceptarLogin = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        entryUser = new javax.swing.JTextField();
        entryPass = new javax.swing.JPasswordField();
        lblUser1 = new javax.swing.JLabel();
        lblMouseEvent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(216, 219, 226));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 543));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imageOn.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 209));

        JpanelLogin.setBackground(new java.awt.Color(216, 219, 226));
        JpanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        JpanelLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JpanelLoginKeyPressed(evt);
            }
        });
        JpanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarLogin.setText("Ingresar");
        btnAceptarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarLoginActionPerformed(evt);
            }
        });
        JpanelLogin.add(btnAceptarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 116, 136, 30));

        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pass.png"))); // NOI18N
        JpanelLogin.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 30));

        entryUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entryUser.setToolTipText("");
        entryUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryUserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryUserMousePressed(evt);
            }
        });
        entryUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryUserActionPerformed(evt);
            }
        });
        entryUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entryUserKeyTyped(evt);
            }
        });
        JpanelLogin.add(entryUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 44, 136, 30));

        entryPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entryPass.setToolTipText("");
        entryPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryPassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryPassMousePressed(evt);
            }
        });
        entryPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entryPassKeyTyped(evt);
            }
        });
        JpanelLogin.add(entryPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 80, 136, 30));

        lblUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        JpanelLogin.add(lblUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 44, 27, 30));

        lblMouseEvent.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblMouseEvent.setForeground(new java.awt.Color(51, 51, 51));
        lblMouseEvent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMouseEvent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JpanelLogin.add(lblMouseEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 170, 19));

        jPanel1.add(JpanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 310, 898, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entryPassKeyTyped
        // TODO add your handling code here:
        //lblMouseEvent.setText("");
    }//GEN-LAST:event_entryPassKeyTyped

    private void entryPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryPassMousePressed
        // TODO add your handling code here:
       //lblMouseEvent.setText("Ingrese su Contraseña");
    }//GEN-LAST:event_entryPassMousePressed

    private void entryPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryPassMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_entryPassMouseClicked

    private void entryUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entryUserKeyTyped
        // TODO add your handling code here:
        //lblMouseEvent.setText("");
    }//GEN-LAST:event_entryUserKeyTyped

    private void entryUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryUserActionPerformed

    private void entryUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryUserMousePressed
        // TODO add your handling code here:
       //lblMouseEvent.setText("Ingrese su usuario");
        
    }//GEN-LAST:event_entryUserMousePressed

    private void entryUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryUserMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_entryUserMouseClicked

    private void btnAceptarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAceptarLoginActionPerformed

    private void JpanelLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JpanelLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpanelLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelLogin;
    public javax.swing.JButton btnAceptarLogin;
    public javax.swing.JPasswordField entryPass;
    public javax.swing.JTextField entryUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMouseEvent;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser1;
    // End of variables declaration//GEN-END:variables
}
